version: '3.4'

services:
  siemens-pedigree-api:
    image: afoone/siemens-pedigree-api
    container_name: pedigree-api
    build:
      context: .
      dockerfile: siemens-pedigree-api/Dockerfile
    networks:
      - pedigree
    ports:
      - 9443:443
      - 9080:80

networks:
  pedigree:
    name: pedigree
